### ISSUE TITLE
Squitch Comparsion

### ISSUE THREAD

**Issue by JeffCarpenter** [amacneil/dbmate#103]
I see you have a comparison table in your readme, but I don't see Squitch in there which has been around for quite a while and would be a good yardstick here.

**Comment by amacneil** [comment]
I'm not familiar with Squitch, and would consider a PR adding it to the readme comparison table. However, judging by Github stars it's not super popular, so I would look for additional data points (commenters also requesting this) before adding it.

**Comment by JeffCarpenter** [comment]
Well I mean [it has been around for eight years](https://metacpan.org/changes/distribution/App-Sqitch)
