### ISSUE TITLE
Add specifying the database url as a command line argument

### ISSUE THREAD

**Issue by defunctzombie** [amacneil/dbmate#105]
While working on wrapper to invoke the command from nodejs, I've found that it would be more flexible to specify the database url via a command line argument rather than having dbmate read it from a `.env` file. This allows the app and testing environment to provide the database url after loading it however it wants.

**Comment by defunctzombie** [comment]
After iterating some more, I think I can get by without this feature by setting the environment variables via the wrapper before exec'ing the command.

I do think this feature is generally useful to unbundle away from the .env file (for those that want that) but I no longer see it as strictly necessary for my needs. I will leave it open for additional comment but feel free to close if no plans or desire to implement.

**Comment by amacneil** [comment]
Yeah, let's keep the feature request open. I agree this is useful in some cases (especially when scripting dbmate) and would be pretty simple to add.

**Comment by rminderhoud** [comment]
This appears to have been added in https://github.com/amacneil/dbmate/pull/150

**Comment by amacneil** [comment]
@rminderhoud thanks
