### ISSUE TITLE
how to use unix_sock with Google cloud platforms: Cloud SQL syntax

### ISSUE THREAD

**Issue by pentium10** [amacneil/dbmate#107]
We have this snippet:

```
FROM node:lts-slim
RUN curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/download/v1.7.0/dbmate-linux-amd64; chmod +x /usr/local/bin/dbmate
WORKDIR /var/www/
COPY . .
ENV DATABASE_URL="postgres://postgres:pass@/bbf_dev?unix_sock=/cloudsql/pg-bbf-instance-dev/.s.PGSQL.5432"
RUN /usr/local/bin/dbmate -e DATABASE_URL migrate
```

it simply fails with the migrate command

```
Step #0: Step 4/10 : WORKDIR /var/www/
Step #0:  ---> Running in ef0ea58fcc5d
Step #0: Removing intermediate container ef0ea58fcc5d
Step #0:  ---> 66c868af67d1
Step #0: Step 5/10 : COPY . .
Step #0:  ---> 2bc0858ba21c
Step #0: Step 6/10 : ENV DATABASE_URL="postgres://postgres:pass@/bbf_dev?unix_sock=/cloudsql/pg-bbf-instance-dev/.s.PGSQL.5432"
Step #0:  ---> Running in 4b06ce1334ac
Step #0: Removing intermediate container 4b06ce1334ac
Step #0:  ---> 12cf38003b1a
Step #0: Step 7/10 : RUN /usr/local/bin/dbmate -e DATABASE_URL migrate
Step #0:  ---> Running in 8429b83962b2
Step #0: [91mError: dial tcp 127.0.0.1:5432: connect: connection refused
Step #0: The command '/bin/sh -c /usr/local/bin/dbmate -e DATABASE_URL migrate' returned a non-zero code: 1
Finished Step #0
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: exit status 1
```

it tries a default 127.0.0.1:5432 but neither the .env file nor the ENV DATABASE_URL is being picked up as we don't have 127.0.0.1 neither in the .env file.

Is something broken? Is there another syntax?

I build another example, with export the var is there, but dbmate is not picking up.

```
Step #0: Step 7/11 : RUN export
Step #0:  ---> Running in b2f14d01c305
Step #0: export DATABASE_URL='postgres://postgres:pass@/bbf_dev?unix_sock=/cloudsql/pg-bbf-instance-dev/.s.PGSQL.5432'
Step #0: export HOME='/root'
Step #0: export HOSTNAME='b2f14d01c305'
Step #0: export NODE_VERSION='12.13.1'
Step #0: export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
Step #0: export PORT='8080'
Step #0: export PWD='/var/www'
Step #0: export YARN_VERSION='1.19.1'
Step #0: Removing intermediate container b2f14d01c305
Step #0:  ---> 9ed92413d49b
Step #0: Step 8/11 : RUN /usr/local/bin/dbmate -e DATABASE_URL migrate
Step #0:  ---> Running in 1bb033a84122
Step #0: [91mError: dial tcp 127.0.0.1:5432: connect: connection refused
Step #0: The command '/bin/sh -c /usr/local/bin/dbmate -e DATABASE_URL migrate' returned a non-zero code: 1
```

the question might be, that it's not picking up the `unix_sock`

see the GCP guide for unix sockets here: https://cloud.google.com/sql/docs/postgres/connect-run

**Comment by amacneil** [comment]
I think the URL format we parse doesn't support unix sockets, so it will probably need a feature to explicitly handle it. The `unix_sock` argument you're using appears to be something specific to sqlalchemy (although dbmate could in theory support the same format). For now I think accessing via tcp is likely the only option.

**Comment by pentium10** [comment]
We cannot use TCP as this runs in a serverless environment. As serverless cannot connect to arbitrary databases, that's why the db support is offered only by unix_sock.With serverless getting more and more usage, you end up getting a lot of complaints. Its not specific to anything. Nodejs works fine with unix_sock.

**Comment by amacneil** [comment]
Understood. I agree that dbmate should support sockets, and I'm open to PRs to fix this, or will do it myself when I get time.

**Comment by natefanaro** [comment]
I know this is an old post but I ran in to a similar issue with attempting to access Cloud SQL instances in Cloud Build. I ended up making an image that runs cloudsql-proxy in the background, allowing dbmate to connect via tcp as usual. Not sure if this would still help you @pentium10 but hopefully someone finds it useful. 

https://hub.docker.com/repository/docker/securenomad/cloudsql-proxy-dbmate

**Comment by karlkfi** [comment]
Seems like the github.com/lib/pq should support sockets in the `host` arg, but i can't get it to work...

From https://pkg.go.dev/github.com/lib/pq?tab=doc#hdr-Connection_String_Parameters

> * host - The host to connect to. Values that start with / are for unix domain sockets. (default is localhost)

**Comment by karlkfi** [comment]
Ahha! Got it working.

Ok so you need a slash at the beginning to indicate no address specified, otherwise your database will be interpreted as the host. Then you need a `host` url parameter pointing to the socket directory.

For example, the `postgres` docker image starts up docker saying:

> listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"

So you have to use `host=/var/run/postgresql` to talk to it:

```
export DATABASE_URL='postgres:///postgres?host=/var/run/postgresql&user=postgres&sslmode=disable'
dbmate up
```

This is useful for init scripts in the `postgres` image, because when it first comes up, it only accepts socket connections. Then it gets restarted listening on `127.0.0.1:5432` for connections from your commands.

**Comment by amacneil** [comment]
Thanks @karlkfi.

In https://github.com/amacneil/dbmate/pull/136 I have added support to specify this via `socket` as well as `host` (for consistency with mysql), and set the port by default.

**Comment by worace** [comment]
Just wanted to say a belated thanks for this discussion and especially to @amacneil for adding this feature. Helped me a lot to get dbmate running in Google App Engine. Cheers!
