### ISSUE TITLE
Feature proposal - wait flag on commands

### ISSUE THREAD

**Issue by Rested** [amacneil/dbmate#111]
:sparkles: When using dbmate as a container, since the base image is distroless, we can't do `dbmate up && dbmate wait` which makes config a bit more cumbersome (e.g. in kubernetes an extra initContainer). If you think this is a good idea I'd be happy to take a shot at implementation.

**Comment by amacneil** [comment]
Sounds good - something like `dbmate --wait up ` seems like a useful command flag if you want to send a PR
