### ISSUE TITLE
dbmate does not generate 'schema.sql' on error in 'dbmate up'

### ISSUE THREAD

**Issue by chrisd1997** [amacneil/dbmate#116]
Whenever an error occurs during `dbmate up`, dbmate does not write the `schema.sql` which makes it impossible to use the `dbmate rollback` command, even though it does generate some tables.

Example:
`Applying: 20200121124611_privacy_policies.sql
Error: Error 1364: Field 'id' doesn't have a default value`

**Comment by amacneil** [comment]
Schema.sql and the rollback command are unrelated. If there is an error during migration and the migration was partially applied, then it is generally unsafe to make any assumptions about the state of the database, so we don't mark the migration as applied (which would be necessary for the rollback command to work as you expect).

Note that with postgresql we apply migrations inside a transaction so you shouldn't get into this state. MySQL doesn't support this functionality so if you have an error during migration it will usually require manual cleanup.
