### ISSUE TITLE
Invoke dbmate from Docker and trigger migration in postgres 

### ISSUE THREAD

**Issue by jayarjo** [amacneil/dbmate#128]
I was trying the following:
```
$ docker run --rm -it --env DATABASE_URL="..." --mount type=bind,source=...,target=/app amacneil/dbmate --no-dump-schema --migrations-dir /app up
```

However I repeatedly get:

```
Error: dial tcp 127.0.0.1:57806: connect: connection refused
```

`DATABASE_URL` points to the postgres server running on another Docker container (not sure how that should matter?)

Do I need to to anything in addition to the above command to be able to run migrations on another Docker container that is running postgres?

**Comment by jayarjo** [comment]
In fact forget about another Docker container, it fails to connect to the postgres on the host as well, with the same error.

**Comment by amacneil** [comment]
By default docker containers have their own network and IP address. There are several ways you can work around this.

If you're running postgres on your local computer you should be able to connect to it by running the dbmate container with [host networking](https://docs.docker.com/network/host/) (I'll add this to the readme):

```sh
docker run --rm --network=host -it amacneil/dbmate
```

If you're running postgres in another container, again there are several ways to solve this. One option is to expose the port from the postgres container to your host (using `-p` flag), then use host networking (as above) when running dbmate:

```sh
docker run --rm -it -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres
docker run --rm -it --network=host -e DATABASE_URL="postgres://postgres:postgres@pg/foo?sslmode=disable" amacneil/dbmate create
```

Another is to put both the postgres container and dbmate on a private container network (and not expose them to the host):

```sh
docker network create mynet
docker run --rm -d -e POSTGRES_PASSWORD=postgres --name=pg --network=mynet postgres
docker run --rm --network=mynet -e DATABASE_URL="postgres://postgres:postgres@pg/foo?sslmode=disable" amacneil/dbmate create
```

Finally, you can also do this using docker compose by adding `depends_on`, which is what [we do](https://github.com/amacneil/dbmate/blob/master/docker-compose.yml) for dbmate development & testing.

**Comment by jayarjo** [comment]
@amacneil thanks for taking your time to clarify this. Would have been great to have this somewhere in readme.

**Comment by amacneil** [comment]
Thanks for the feedback - I updated the readme.
