### ISSUE TITLE
Subdirectories and multiple migration directories

### ISSUE THREAD

**Issue by rlander** [amacneil/dbmate#142]
It doesn't seem possible to point to multiple directories with the `-d` flag and subdirectories don't seem to be handled by dbmate. Are there plans to support subdirectories/multiple migrations directories? 

Edit: I should add that this is a great tool!

**Comment by amacneil** [comment]
Hi - thanks for the feedback!

Can you explain what you mean by multiple directories? You want to use two at once, or just to switch between two sets of migrations?

**Comment by rlander** [comment]
Sure! In one of the projects I'm currently working on, migrations are split into separate directories within the main migrations directory, like:

- migrations/
  - foo_migrations/ 
  - bar_migrations/

Our current migrations system picks up all the subdirectories within the `migrations/` directory.

**Comment by amacneil** [comment]
Interesting. Can you share more about what you're trying to achieve with this folder structure? Would you ever apply migrations from only one directory?

**Comment by rlander** [comment]
> Can you share more about what you're trying to achieve with this folder structure? 

To build our system (written in Clojure), we package multiple logical apps (each app having it's own migrations) into a single JAR. Static resources like migration files must be stored in a `resources/` directory in order to be discoverable within a JAR. So each sub-directory corresponds to a specific app's migrations.

> Would you ever apply migrations from only one directory?

Yes, in some cases we apply migrations from only one directory, especially when testing in staging.

We're assessing moving our system to `dbmate`, but the fact that all migrations have to be in a single directory is a non-starter for us and, since I couldn't find a public roadmap, I opened this issue. Hope that's ok and thanks for listening!

**Comment by amacneil** [comment]
No problem!

So I think the `--migrations-dir (-d)` flag will work for this. You should be able to run `dbmate -d ./db/foo_migrations` to run all the migrations in that directory.

If you want to run migrations for multiple directories I think you would need to loop over them (shell wildcards might work).

**Comment by rlander** [comment]
Well, that's a good point. Now that I think of it, a simple bash script + `-d` will probably do the trick for our use case. Thanks!
