### ISSUE TITLE
Postgres connection fails if password has a % character

### ISSUE THREAD

**Issue by chapm250** [amacneil/dbmate#143]
Using dbmate 1.9.0 and when running dbmate with a env variable throws the error `invalid URL escape`

**Comment by amacneil** [comment]
Since it's a URL, you probably need to use `%25` instead of `%` to specify a percent sign. See [url encoding](https://en.wikipedia.org/wiki/Percent-encoding).

**Comment by chapm250** [comment]
It looks like that worked! It's a little awkward due to some integrations with vault, so I'd prefer if we could leave this open and I can look into how to automatically escape for URLs using something like https://golang.org/pkg/net/url/#QueryEscape

**Comment by amacneil** [comment]
Great!

Dbmate expects the connection string in URL format, so we're not going to change to a non-standard URL parsing (which would break any legitimately percent-escaped characters). However, if it's a problem you could construct the URL on the fly based on fields pulled from vault.
