### ISSUE TITLE
Using env vars in migrations

### ISSUE THREAD

**Issue by armand1m** [amacneil/dbmate#162]
Currently, when creating roles in the database I cannot rely on a static password because then it would be checked against version control.

I'm wondering if there is a way I can write something like this:
 
```sql
-- migration:up
CREATE ROLE some_role WITH PASSWORD "${SOME_ROLE_PASSWORD}";

-- migration:down
DROP ROLE some_role;
```

**Comment by amacneil** [comment]
There has been some discussion of this feature in https://github.com/amacneil/dbmate/issues/118 - let's continue it there. This isn't possible today, but you could achieve the same thing with a simple `psql` one-liner.
