### ISSUE TITLE
Ability to rename schema_migrations table

### ISSUE THREAD

**Issue by amacneil** [amacneil/dbmate#168]
Breaking out suggestion from [this comment](https://github.com/amacneil/dbmate/issues/110#issuecomment-711141575):

It would be nice to have the ability to specify a custom name for the `schema_migrations` table. This could be supported via a `--migrations-table` option or `$DBMATE_MIGRATIONS_TABLE` env variable.

**Comment by matt-snider** [comment]
I'm currently trying to use dbmate to provide seed data during development. I've set up a shell command `dbmate-seed` to just run `dbmate --migrations-dir ./db/seed $@`. This works very nicely and allows me to store both migrations and seed data without mixing them up.

The only issue is that both migrations are stored in the same table, so when rolling back it will fail with `Error: can't find migration file: 20201112161533*.sql` for seed data migrations.

Extending the command with `--migrations-table seed_schema_migrations` would solve this issue!

Just wanted to chime in with my own use case. Thanks for a great tool! :-)

**Comment by amacneil** [comment]
Interesting use case. If your seeds are in one file, is there a reason you can't just use `psql` (or similar if mysql) to apply it?

**Comment by matt-snider** [comment]
@amacneil They aren't in one file. They mirror the structure of `db/migrations` so `db/migrations/20201112161533_animals.sql` would have a corresponding `db/seed/20201112161533_animals.sql` file.

It's convenient to be able to split migrations up that way, but admittedly it's more of an organizational benefit than a functional one.

Maybe it's better to implement this outside of dbmate.
