### ISSUE TITLE
Support cloudsql-proxy drivers

### ISSUE THREAD

**Issue by pablocrivella** [amacneil/dbmate#176]
I'm using dbmate from inside a golang service and I'm trying figure out if it's possible to use it with the https://github.com/GoogleCloudPlatform/cloudsql-proxy drivers.

This is how google docs says it should be used:

```go
import (
    "github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/mysql"
)
...
cfg := mysql.Cfg(INSTANCE_CONNECTION_NAME, DATABASE_USER, PASSWORD)
cfg.DBName = DATABASE_NAME
db, err := mysql.DialCfg(cfg)
```
from: https://cloud.google.com/sql/docs/mysql/connect-external-app#go

Related:

https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/proxy/dialers/mysql/hook.go
https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/proxy/dialers/postgres/hook.go

**Comment by amacneil** [comment]
If you're deploying on GCP or App Engine I believe you should be able to connect to the socket directly (using `?socket` parameter as documented in the readme).

Otherwise, if you need to manually run this proxy I would recommend running it as a separate process (using the examples on their readme, or step 6 on those docs you linked) rather than trying to import it as a go library.

**Comment by pablocrivella** [comment]
Yeah now I'm running the proxy as a sidecar on my pod, but I was having some weird connection issues (related to istio-proxy I think) and wanted to try some stuff 😅 

Anyway, thanks for your reply @amacneil!

**Comment by apognu** [comment]
I wish this would be revisited as:

 * Google themselves present [SQL proxy through code](https://cloud.google.com/sql/docs/postgres/samples/cloud-sql-postgres-databasesql-connect-connector) as one of the recommended approaches
 * Some deployments cannot use a sidecar process (when Cloud Run must connect through Private Service Connect, for example).

Having the ability to set up a custom dialer would help greatly.
