### ISSUE TITLE
`dbmate dump` fails when `search_path` is set

### ISSUE THREAD

**Issue by heri16** [amacneil/dbmate#180]
`dbmate dump` fails when `search_path` is set in `DATABASE_URL="postgres://postgres:postgres@127.0.0.1:5432/db1?search_path=app_public,app_private,app_hidden,public&sslmode=disable"`

```
pg_dump: [archiver (db)] connection to database "" failed: invalid URI query parameter: "search_path"
```

**Comment by amacneil** [comment]
This is fixed on master (https://github.com/amacneil/dbmate/pull/166). I will release a new version in the next couple days, in the meantime if you need search_path support you can build the latest master with `go get -u github.com/amacneil/dbmate`.

**Comment by heri16** [comment]
Looking forward to the new release. Thanks for the help!
