### ISSUE TITLE
Dump doesn't work using dbmate docker container and latest Postgres.

### ISSUE THREAD

**Issue by lukeggchapman** [amacneil/dbmate#183]
When running "dump" you get this error:
`Error: pg_dump: error: server version: 13.1 (Debian 13.1-1.pgdg100+1); pg_dump version: 12.4`

When running "up" dumping the schema fails silently.

SQL clients added to the docker container in #157 need updating.

**Comment by amacneil** [comment]
Thanks. I think we are already running the latest version of alpine so it might just be a case of waiting for them to upgrade.

**Comment by amacneil** [comment]
Looks like postgres 13 will be included with the next version of alpine linux, which should be released in the next month or so. In the meantime, if this is critical for you you could build the Dockerfile yourself and simply change the `FROM alpine as release` line to `FROM alpine:edge as release`.

**Comment by lukeggchapman** [comment]
No problems, just wanted to raise it here for any others that have the same problem.
Now that I know what it is, it is easy to work around.

Thank you!!
