### ISSUE TITLE
Add Documentation and Better Error Handling Around DBMATE_MIGRATIONS_TABLE

### ISSUE THREAD

**Issue by ClaytonNorthey92** [amacneil/dbmate#185]
When running `dbmate dump`, my previous database migration tool used `schema_migrations` for its migration table.  This is what [dbmate defaults to](https://github.com/amacneil/dbmate/blob/61771e386d75a18943149b14c03a9cfa304d363c/main.go#L59) so I was getting an odd, not-very-helpful error:
```
Error: pq: column "version" does not exist
```

I had to dig through the logs to find that dbmate was expecting that on the `schema_migrations` table.  There is a little info in the `README` but it is not much and it does not tell a user how to change the table name. 

I want to request the following:
* description of this environment variable in the README, and what it defaults to
* a better error if there seems to be something unexpected with the table with the name of the env variable `DBMATE_MIGRATIONS_TABLE`
  * possibly a check for the `version` column, and an error saying "attempting to use \<table name\> for the migrations table, but the schema was not as expected, was this table being used for something else?"

I would be happy to work on this issue if you agree with the idea.

**Comment by ClaytonNorthey92** [comment]
I do also realize the `help` message shows information about this variable, I think it would still be helpful to have more in the `README`

**Comment by amacneil** [comment]
Thanks for the feedback - I updated the readme. 

It might be possible to catch that error and print a more helpful message - if you want to submit a PR I'm open to it. For postgres you could probably check the error code ([example](https://github.com/amacneil/dbmate/blob/454f93a000efe61719a52215e082ef3bd0c40785/pkg/driver/postgres/postgres.go#L228-L229)), but I'm not sure off hand how to best do it for the other drivers.

**Comment by ClaytonNorthey92** [comment]
Thanks @amacneil , I can look into adding a PR for a more helpful error message 👍
