### ISSUE TITLE
Any way to dump data with schema?

### ISSUE THREAD

**Issue by ClaytonNorthey92** [amacneil/dbmate#188]
Is there any way to dump data with the database schema in both `dbmate dump` and `dbmate migrate` when dumping after the migration?

I see that [the --schema-only flag is added here](https://github.com/amacneil/dbmate/blob/master/pkg/driver/postgres/postgres.go#L175) when dumping postgres, and [here (the mysql equivalent) when dumping mysql](https://github.com/amacneil/dbmate/blob/454f93a000efe61719a52215e082ef3bd0c40785/pkg/driver/mysql/mysql.go#L128).  I am assuming this is consistent across supported database technologies.

This is also called [after the migrations have been run](https://github.com/amacneil/dbmate/blob/master/pkg/dbmate/db.go#L383).

I would like to propose a way (if it does not exist yet) to allow a user to include data in their dumps.

I would vote a flag `--include-data`, which, when present, would ensure the dump would include data for both `dump` and `migrate` commands.  This could have an environment variable of `DBMATE_INCLUDE_DATA=<0/1>`.

I would be happy to work on the PR for this 

I don't see a way to

**Comment by amacneil** [comment]
Can you explain your workflow? This doesn't seem to be a feature needed by a database migration tool, since you can always just run `pg_dump` (or equivalent) yourself.

**Comment by ClaytonNorthey92** [comment]
hey @amacneil I am going to close this...was working on something where I thought this was needed, but it was just some bad practices in my code base that I have a better fix (that is not related to `dbmate`) for.

thanks for the quick response though 👍
