### ISSUE TITLE
-s flag doesn't work?

### ISSUE THREAD

**Issue by fr3fou** [amacneil/dbmate#190]
![image](https://user-images.githubusercontent.com/1344906/103387428-691b0000-4b0c-11eb-84a0-d07b7307a733.png)

**Comment by fr3fou** [comment]
Oh, I'm supposed to pass the flags before the command, like `up`, my bad.

**Comment by fr3fou** [comment]
Hmm, even after placing the arguments in the correct order, the file still wasn't generated

**Comment by amacneil** [comment]
There’s probably an issue running the dump command. It fails silently during migrate.

Try running dbmate dump and see what it says.

**Comment by fr3fou** [comment]
![image](https://user-images.githubusercontent.com/1344906/103446005-537c1680-4c83-11eb-855f-b656d1915753.png)
Seems like the ubuntu version of pg_dump is outdated

**Comment by amacneil** [comment]
I think Postgres 13 only came out a couple months ago, so that’s probably why. In any case if you want it to work then please ensure your pg dump version matches what you’re using on the server.
