### ISSUE TITLE
Support Sqlite Pragmas in Migrations

### ISSUE THREAD

**Issue by ak5** [amacneil/dbmate#217]
Currently with latest version (dbmate version 1.12.0) I cannot do:

```sql
PRAGMA journal_mode = WAL;
```

with the error:

```
Error: cannot change into wal mode from within a transaction
```

It would be nice to be able to rely on migrations to setup my databases completely without having to remember to change pragmas manually or via application code

**Comment by amacneil** [comment]
It should work if you use the `migrate:up transaction:false` flag in your migration file.
