### ISSUE TITLE
postgres automatic peer auth

### ISSUE THREAD

**Issue by wraithm** [amacneil/dbmate#229]
Currently, it's possible to connect to a database on localhost using a domain socket. For example:

```
$ dbmate -u "postgres:///database_name?socket=/var/run/postgresql" status
```

It'd be really nice if this was autodetected and you could just do:

```
$ dbmate -u postgres:///database_name status
```

The following works well on my machine:

```
$ psql postgres:///database_name
```

I believe that `psql` is using the `peer` authentication method on my local machine over the domain socket that postgres exposes.

Some more info:
https://www.postgresql.org/docs/current/auth-peer.html

**Comment by amacneil** [comment]
We currently assume localhost if no hostname is given, but I think assuming unix socket is a reasonable idea (it seems less surprising than our current behavior). If any hostname is given in the URL we should continue to assume TCP.

I haven't looked into peer authentication with the [pq](https://github.com/lib/pq) library we use, but I assume it's working if your first example works already?

If you care to submit a PR adding this (with tests) to postgres I'll merge it. It should probably live in this function: https://github.com/amacneil/dbmate/blob/main/pkg/driver/postgres/postgres.go#L38

**Comment by wraithm** [comment]
Yeah, I'll give it a shot! Thanks for the direction.
