### ISSUE TITLE
Homebrew version does not have proper build flags

### ISSUE THREAD

**Issue by CGamesPlay** [amacneil/dbmate#247]
The homebrew formula for dbmate installs a version of dbmate which does not have the same build flags as the version distributed in the github release. Specifically, `ENABLE_JSON1` and `OMIT_LOAD_EXTENSION` are not included in the homebrew formula.

Impact: If you use JSON functions in your migrations, they fail if you install dbmate using homebrew.

Workaround: download the binary directly from github.

**Comment by Enrico204** [comment]
I think that you should open an issue in the Homebrew repository, as build configs are in that repository: https://github.com/Homebrew/homebrew-core

**Comment by amacneil** [comment]
Will be fixed by https://github.com/Homebrew/homebrew-core/pull/94150
