### ISSUE TITLE
Support for separating the application schema from the db-mate control schema (proposal)

### ISSUE THREAD

**Issue by zigster64** [amacneil/dbmate#248]
## Background

We have an existing set of applications that we are looking at applying db-mate to.

Each application will be storing its data in an application-specific schema inside a shared database.  (db-mate already works with this)

For security reasons, we want to separate out the db-mate control tables from the application data.  We also want the normal postgres user that the service uses to NOT have alter table / create table / drop table access to the data in its schema.  The postgres user that db-mate uses would have access to do all these things on the service schema though.

So we are looking at having : 
- A "application data" schema per application
- A "db-mate control" schema per application, just for the db-mate data
- Running db-mate reads its control info and migrations from one schema, and then applies the DDL and other updates to another schema later on

## Proposal

If we put the work in to do the above - allowing for a (totally optional) complex separation of schemas and permissions ... would this be considered generally useful enough to merge upstream ?

## Other Considerations 

... dont want to end up adding unnecessary complexity to db-mate that can be easily broken by accident
... dont want to end up having to maintain a fork, if we do modify db-mate !!!   (you know the feeling, hey)

thanks

**Comment by amacneil** [comment]
I think you might already be able to do this today. You can override the location for the `schema_migrations` table ([docs](https://github.com/amacneil/dbmate#schema_migrations-table)), including prefixing it with a different postgres schema.

Would that meet your needs, or did I misunderstand?

**Comment by zigster64** [comment]
That sounds like a slick solution.  

I think you are right, just passing `--migrations-table` as a param will do exactly that, and that's pretty much all we will need.

Will give it a go, and see if that makes it do what we want.

**Comment by Enrico204** [comment]
@zigster64 Can you provide a feedback on this? I'm quite interested for a future project :-)

**Comment by amacneil** [comment]
Closing since if I understand the above thread correctly, this is already possible.
