### ISSUE TITLE
Comparison of dbmate vs sqitch or flyway

### ISSUE THREAD

**Issue by halostatue** [amacneil/dbmate#249]
Both [sqitch](http://sqitch.org) and [flyway](https://flywaydb.org/download/community) are mature alternatives that would be good to add to your comparison, although they have somewhat larger requirements (Perl for sqitch, Java for flyway).

**Comment by halostatue** [comment]
One of the things that’s really nice about `sqitch` is that it has three pieces to each migration, each as a separate file:

- up
- down
- verify

The verify step encourages people to write a query that confirms that the migration happened successfully. It can also integrate with `pgTAP` for Postgres, to enable unit testing.

**Comment by Enrico204** [comment]
Nice tools. Are you willing to propose a change in the comparison table by opening a pull request? :-)

**Comment by Enrico204** [comment]
Good! We can integrate sqitch now, and then see if anyone else uses flyway :-)
