### ISSUE TITLE
Can dbmate show the final database schema in a nice and structured way?

### ISSUE THREAD

**Issue by JanmanX** [amacneil/dbmate#257]
When working on a project, it is nice to be able to see the source definition of each table/function/role/etc.
For instance, right now I am working on a project where the SQL files are separated as such:
```
├── migrations
│   ├── 0001.sql
│   └── 0002.sql
└── schema
    ├── functions
    │   ├── func1.sql
    │   └── func2.sql
    ├── roles
    │   └── role1.sql
    └── tables
        ├── table1.sql
        └── table2.sql
```

When a developer wants to know about a table, they can inspect the source file.

However, when working with migrations, it is not really possible. The only solution is to dump the whole database and inspect this one large SQL file.

Is it possible to manage a project with dbmate such that you can still have such a project structure? 
Or maybe there is even a better way to maintain a project like this?

**Comment by gmhafiz** [comment]
You can use mysqldump and `pg_dump` if you want to know the schema? Use `--no-data` for mysql and `--schema-only` for postgres

`mysqldump --no-data -h 127.0.0.1 -u user -p db table_name > schema.sql`

For postgres

`PGPASSWORD=password pg_dump --username user --table table_name --schema-only  db_name" > table_schema.sql`

**Comment by JanmanX** [comment]
@gmhafiz I do realize I can dump each table and inspect them, but it feels rather tedious to do, especially since this needs to be done every time anything changes.

Say that I am a new developer on my project, and I quickly want to understand the table structures. To me it seems much easier to have it neatly organized in a nice file-structure as shown above and have the IDE utilize those files, rather than having to dump each table when needed.

Perhaps my way of working with database management can be improved?

**Comment by gmhafiz** [comment]
In reality, we use software like goland that has built-in capability that can generate DDL.

![image](https://user-images.githubusercontent.com/1927253/149843311-e346b153-4b4b-40b0-9bfe-6cf7276f538b.png)

I am not sure if a migration tool like dbmate is the right tool to view your table schema when many other software can do the same job.

**Comment by amacneil** [comment]
Thanks for the request. As others mentioned above, I think this isn't really something dbmate is designed to do.

We do support writing the `schema.sql` file (one file for the whole database), which is designed to help with code review and allow people to look at not just a migration file, but a diff of one database schema to the next. However, breaking that into a separate file per table would be a lot of extra work for an unclear benefit.
