### ISSUE TITLE
Windows defender falsely reports trojan

### ISSUE THREAD

**Issue by rminderhoud** [amacneil/dbmate#262]
Windows defender falsely detects a trojan in the windows build (1.13.0). Ran it on virus total and it's basically the only platform to report it as a virus. Not sure if this can be resolve some how (send msft a build, code sign the exe?) but wanted to post here:

https://www.virustotal.com/gui/file/cf7174d63cab975cb3773d983188ab8920e91092e70f26bf1e299059951962ca?nocache=1

**Comment by amacneil** [comment]
Urgh. I don't know how to avoid that without buying an EV code signing cert.

That seems like more than just the typical "this developer is untrusted"? What warning do you see?

**Comment by rminderhoud** [comment]
It's ugly, after downloading the file and trying to move it around in win explorer or added the `.exe` extension:

![image](https://user-images.githubusercontent.com/1752584/150042941-a176e58c-2a4a-416d-97ea-704ed41dd8e7.png)

Windows then proceeds to quarantine the item. If I try to access the binary directly from the command line using powershell it prompts be to select a launcher (as I can't set the `exe` extension):

![image](https://user-images.githubusercontent.com/1752584/150043242-d27c69ea-3e30-456b-bdb2-613b62fe6e55.png)

If I run using git bash (msys2 terminal), I get a permission denied error:

```
Ralph@RAM-DESKTOP-WIN10 MINGW64 ~/Downloads
$ ./dbmate-windows-amd64
bash: ./dbmate-windows-amd64: Permission denied
```

Adding an exclusion for it in windows defender solves the problem but is not idea. Wish I had a solution here, not sure which part of the executable is triggering a match in signatures.

**Comment by rminderhoud** [comment]
Seems that there is precedent for this false positive: https://answers.microsoft.com/en-us/protect/forum/all/false-positive-win32sabsikftaml/5aa91237-fb7f-4dff-a868-09737cc2bfca

**Comment by rminderhoud** [comment]
Might be of interest: https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by rminderhoud** [comment]
> Seems that there is precedent for this false positive: https://answers.microsoft.com/en-us/protect/forum/all/false-positive-win32sabsikftaml/5aa91237-fb7f-4dff-a868-09737cc2bfca

Okay updating my system to windows 2H12 resolve the issue. I guess that forced the windows defender signatures to be updated as well and it no longer flags the exe! Going to close this issue as it's not an issue with up to date signatures.

**Comment by amacneil** [comment]
😅 glad you fixed it
