### ISSUE TITLE
DATABASE_URL doesn't support whitespaces

### ISSUE THREAD

**Issue by azerpas** [amacneil/dbmate#264]
I was testing the tool with a path containing a whitespace and this happened

```
Error: unable to open database file: no such file or directory
```

## Reproduce

`dbmate-x86_64-apple-darwin -u "sqlite:/Users/USERNAME/Library/Application Support/store.sqlite3" status`

**Comment by Enrico204** [comment]
Apparently, the behavior on Linux is different (it works, but not as expected):
```sh
$ dbmate -u "sqlite:/tmp/te st.db" create
Creating: /tmp/te%20st.db
```

I suspect that the problem is in the connection string parsing with `url.URL`. Which version of `dbmate` are you testing?

**Comment by Enrico204** [comment]
I've found the issue: absolute paths are parsed differently in `url.Parse`. In fact, spaces in relative URLs are handled correctly:
```sh
$ dbmate --url "sqlite3:../../../../../../tmp/te st.db" create
Creating: ../../../../../../tmp/te st.db
```

**Comment by azerpas** [comment]
> I've found the issue: absolute paths are parsed differently in `url.Parse`. In fact, spaces in relative URLs are handled correctly:
> 
> ```shell
> $ dbmate --url "sqlite3:../../../../../../tmp/te st.db" create
> Creating: ../../../../../../tmp/te st.db
> ```

Great work!
