### ISSUE TITLE
store description in schema_migrations as well?

### ISSUE THREAD

**Issue by matthewlenz** [amacneil/dbmate#27]
Would be nice if the migration description in addition to the version was stored in the db.

**Comment by amacneil** [comment]
If by description you mean the file name, I'm not sure what the advantage is? It's intentional that you can rename migration files if you need without breaking the database.

**Comment by amacneil** [comment]
Closing as something I don't plan to support unless there is a really strong case for it, since I would like to avoid adding additional columns to the `schema_migrations` table.
