### ISSUE TITLE
unsupported driver: postgresql

### ISSUE THREAD

**Issue by billysutomo** [amacneil/dbmate#275]
I'm trying to integrate dbmate into my existing go code. 
But i got error `unsupported driver: postgresql`, I already import `_ "github.com/lib/pq"` , 
here is my postgre connection `postgresql://root:root@localhost:5432/dbname?sslmode=disable`
any guidance?

**Comment by rohitpaulk** [comment]
@billysutomo could you clarify what you mean by "integrate dbmate into my existing go code"? 

Are you trying to import go code from this repository, or are you using the binary? If you're importing go code, a small script to reproduce the issue would be useful. 

fwiw, here's where the postgres driver is registered: https://github.com/amacneil/dbmate/blob/519f186c8a3daec086608b2c21677c672eda56db/pkg/driver/postgres/postgres.go#L18-L21.

**Comment by billysutomo** [comment]
@rohitpaulk yeah I'm trying to import go code from dbmate repository.
Looks like I found the solution, I need to import `_ "github.com/amacneil/dbmate/pkg/driver/postgres"` to initiate the `postgres` driver.
Thanks for the guidance 😄
