### ISSUE TITLE
dbmate dump against cockroachdb failed

### ISSUE THREAD

**Issue by andyli** [amacneil/dbmate#279]
```
$ dbmate dump
Error: pg_dump: error: query failed: ERROR:  column "x.tableoid" does not exist
pg_dump: error: query was: SELECT x.tableoid, x.oid, x.extname, n.nspname, x.extrelocatable, x.extversion, x.extconfig, x.extcondition FROM pg_extension x JOIN pg_namespace n ON n.oid = x.extnamespace
```

The mentioned query ran fine without selecting `x.tableoid`. Not sure whether the remaining queries will succeed or not.

My CockroachDB version:
CockroachDB CCL v21.2.6 (x86_64-unknown-linux-gnu, built 2022/02/22 18:30:37, go1.16.6)

Maybe dbmate should make use of [SHOW CREATE ALL TABLES](https://www.cockroachlabs.com/docs/stable/cockroach-dump.html) when it detects the db is CockroachDB.

**Comment by rohitpaulk** [comment]
Related: https://github.com/cockroachdb/cockroach/issues/20296

**Comment by amacneil** [comment]
I am going to close this, because it looks like we do not support CockroachDB, and I have no plans to add it. If someone would like to submit as PR for this I'm open to it.

**Comment by kishaningithub** [comment]
@amacneil If you convert libpq to pgx you will get cockroach db support out of the box https://github.com/amacneil/dbmate/discussions/595
