### ISSUE TITLE
Command to show status of available vs applied migration files

### ISSUE THREAD

**Issue by matthewlenz** [amacneil/dbmate#28]
$ ls -1
20170123192101_testing.sql
20180123192101_testing.sql

Maybe something like:

./dbmate -d . status

revisision, status
20170123192101_testing, APPLIED
20180123192101_testing.sql, UNAPPLIED

**Comment by amacneil** [comment]
I agree, this would be a helpful feature. I'll look at adding it to the next version (or PRs welcome 😄)

**Comment by hmleal** [comment]
Please check the pull request #32

**Comment by fourcube** [comment]
This would be very useful to me as well! 

@hmleal are you still interested in finishing this? I'd be happy to work on this if you can't find the time.
