### ISSUE TITLE
support env

### ISSUE THREAD

**Issue by talpa** [amacneil/dbmate#280]
it is possible add support for environment inside sql script?
for example  my docker  

`docker run my_db_container dbmate -e "VALUE_A=10" -e "VALUE_B=20" -e "VALUE_C=30" `

```
-- migrate:up
insert into table (a,b,c ) values(${VALUE_A},${VALUE_B},${VALUE_C}); 
-- migrate:down
```

**Comment by rohitpaulk** [comment]
@talpa I'd like to understand your use-case better, could you explain what you'd use this feature for?

**Comment by amacneil** [comment]
Dupe of https://github.com/amacneil/dbmate/issues/118

**Comment by amacneil** [comment]
I’m not totally against adding this feature if someone wants to work on it, but I think there are a bunch of edge cases (like schema.sql generation, whether we provide sql injection protection) that make it a potential source of more confusion and maintenance burden. 

In the meantime the best way to solve this is just have a normal sql script that you execute manually using `psql` after running dbmate.
