### ISSUE TITLE
Consider conditional inclusion of sqlite driver due to cgo

### ISSUE THREAD

**Issue by cloneable** [amacneil/dbmate#284]
Hi! Would you be open to consider making the SQLite driver optional due to CGo, compilation time and dependencies? This could be achieved by moving the `_ "github.com/amacneil/dbmate/pkg/driver/sqlite"` import into a `main_cgo.go` file which then also contains the `//go:build cgo` directive. (Maybe the `_cgo` suffix is already special and we don't need the directive. I don't know.)

main_cgo.go:
```go
//go:build cgo
// +build cgo

package main

import (
	_ "github.com/amacneil/dbmate/pkg/driver/sqlite"
)
```

**Comment by amacneil** [comment]
I’m pretty sure this is already the case. Did you try `CGO_ENABLED=0` ?

**Comment by cloneable** [comment]
This can't work because main.go unconditionally imports the driver package, but without cgo that package doesn't contain any buildable files.

```shell
$ CGO_ENABLED=0 go install github.com/amacneil/dbmate@latest
package github.com/amacneil/dbmate
	imports github.com/amacneil/dbmate/pkg/driver/sqlite: build constraints exclude all Go files in $HOME/.go/pkg/mod/github.com/amacneil/dbmate@v1.14.0/pkg/driver/sqlite
```

**Comment by amacneil** [comment]
That’s interesting, it used to work. Maybe that was before I refactored each driver into a separate package. 

I’m open to the changes you proposed.
