### ISSUE TITLE
Special chars in db password

### ISSUE THREAD

**Issue by keomaborges** [amacneil/dbmate#289]
I'm not sure if it's really a bug, but recently I changed the password of my database and faced authentication issues.

The string was basically letters, numbers and a `+`.  Something like `abc123+def456`. I tried different strategies to try to escape the password, with no lucky though.

Then I updated the password to only letters and numbers. The string connection started to work again. My DB is MySQL 5.7.

**Comment by ecumene** [comment]
I managed to connect to my database which has special characters.

You just need to escape your shell's syntax. For example, I'm using `zsh` so `wow!cool!` becomes `wow\!cool\!`.

Like I said, it depends on your shell. But try `abc123\+def456`

```
dbmate --url "mysql://admin:wow\!cool\!@127.0.0.1/production" up
```

**Comment by keomaborges** [comment]
Okay, that escaping fixed the issue. Thank you.

**Comment by renevall** [comment]
I solved this issue by using

```go
connString := fmt.Sprintf(`postgres://%s:%s@%s:%d/%s?sslmode=disable`,
		user, url.QueryEscape(password), host, port, dbname)
```

Now I can use special characters in passwords.
