### ISSUE TITLE
rollback: export ErrNoRollback to rollback all

### ISSUE THREAD

**Issue by gnuletik** [amacneil/dbmate#292]
Hi,

First, thanks for this great project!

I'm integrating dbmate as a golang library in my project and, in order to test all migrations, I want to apply all rollback migrations until the original state.
To achieve this, I'm using the following function:
```go
func rollbackAll(mate *dbmate.DB) error {
	for {
		err := mate.Rollback()
		if err == nil {
			continue
		}
		// no more migration to rollback
		if err.Error() == "can't rollback: no migrations have been applied" {
			return nil
		}
		if err != nil {
			return err
		}
	}
}
```

In order to avoid issues with future upgrades, would it be possible to export the following error as a global ?

https://github.com/amacneil/dbmate/blob/1613f72c4f9456ebe1b72eb1fa8a55c648a7587a/pkg/dbmate/db.go#L483

like:

```go
const ErrNoRollback = errors.New("can't rollback: no migrations have been applied")
```

I can make a PR if that sounds good to you.

This issue is linked to https://github.com/amacneil/dbmate/issues/221 and https://github.com/amacneil/dbmate/pull/256 but it allows more flexibility when using it as a library.

Thanks!

**Comment by amacneil** [comment]
Hi! Yes that seems like a good idea - PR welcome

**Comment by gnuletik** [comment]
Great ! PR done.

I can also implement the `RollbackAll()` func in a separate PR if you want.

**Comment by amacneil** [comment]
Yeah you could make a PR for rollbackAll too. Curious what you use it for? Why don’t you just truncate or drop all tables?

**Comment by pawndev** [comment]
> Great!
> 
> I'm using it in a go test which:
> 
>     * Creates a temporary database and run all migrations up
> 
>     * Rollback all migrations to the initial state
> 
>     * Re-run all migrations up
> 
> 
> It helps catching missing statements in `migrate:down` blocks.
> 
> For example, if there is a missing `DROP TABLE`, the last up function will fails with an error like `TABLE "something" already exists`.

Not a bad idea. I'll do that in my project too.
Thank you !

**Comment by gnuletik** [comment]
Happy to help :)

For the reference, I created the PR for the RollbackAll func : https://github.com/amacneil/dbmate/pull/303
