### ISSUE TITLE
Symbol limitations in password when parsing db URL

### ISSUE THREAD

**Issue by nenkie** [amacneil/dbmate#309]
Hi,

We have following config .env file with quite protected password which can't be parsed by dbmate:

```DATABASE_URL="mysql://super_user:kk/Q>`78N5$JJJJJJJJJXXXXX@super_server:3306/dbmate_poc"```

Above URL results in the following error:

`Error: parse "DATABASE_URL": invalid port "**:kk**" after host`

If I remove **/** symbol from password than error is the following: 

`Error: parse "DATABASE_URL": net/url: invalid userinfo`

In order that to work, I have to remove **/**, **`** and **>**, symbols. Is that expected that such symbols are not supported when parsing url?

**Comment by amacneil** [comment]
have you tried url encoding the password? e.g. `kk%2FQ%3E%6078N5%24JJJJJJJJJXXXXX`
