### ISSUE TITLE
Skipping certain schemas / tables during dump (Postgres)

### ISSUE THREAD

**Issue by knpwrs** [amacneil/dbmate#324]
Is there a way to skip dumping certain schemas, tables, etc? I am using [Postgraphile](https://www.graphile.org/postgraphile/), and in development it creates a schema called `postgraphile_watch` and places a number of functions and other stuff there. This schema is only relevant to the local development process, not to other developers or to production environments. Is there a way to skip this schema during dump?

**Comment by amacneil** [comment]
I don't think so, but you could create a postgres user to run migrations that doesn't have access to that schema.

**Comment by knpwrs** [comment]
Interesting. Can you think of a clean way to bootstrap that as a part of the migration process, or would creating the roles and schemas be part of the infrastructure as code bootstrap process?

Right now, in development using Docker, I'm thinking I would have to use the [`/docker-entrypoint-initdb.d` directory](https://github.com/docker-library/docs/blob/cb7e4ee1d4ff30913e89601be985bc4c8c49d579/postgres/README.md#initialization-scripts) to set up the roles and schemas. Then depending on the target platform I would need to replicate that setup (it seems like Terraform has some Postgres providers that could handle this).

Does that make sense? Am I missing something that could make it simpler?

**Comment by knpwrs** [comment]
Well, this could be simpler: I only need the roles setup that way for development. In production I don't need the migration role to not have access to the `postgraphile_watch` schema because 1.) it won't exist and 2.) the dump won't matter in production anyway because it's only committed in development.

Thank you for the input!
