### ISSUE TITLE
Error: packet for query is too large.

### ISSUE THREAD

**Issue by atimonin** [amacneil/dbmate#328]
I'm trying to use dbmate for initially set some values in database.
It's rather large number of sql INSERT's, file length is 53071547 (a bit less than 64MB)
And when I try to do "dbmate up" I get:
Error: packet for query is too large. Try adjusting the 'max_allowed_packet' variable on the server
I checked on server:
mysql> show variables like 'max_allowed_packet';
+--------------------+----------+
| Variable_name      | Value    |
+--------------------+----------+
| max_allowed_packet | 67108864 |

So on server side it at least should fit...

It looks like dbmate is trying to push all SQL statements in one big packet and it is limited on client side (I may be wrong).
May it be possible to push SQL statements one-by-one?

**Comment by amacneil** [comment]
Unfortunately it is not possible to push the SQL statements one by one, that would require parsing the SQL (and accounting for differences across dialects) which is beyond the scope of this library.

Maybe the simplest solution here is to break this up into two migration files.
