### ISSUE TITLE
version command

### ISSUE THREAD

**Issue by MarkMurphy** [amacneil/dbmate#33]
Would be nice to have a `dbmate version` command that prints the current schema version.

**Comment by amacneil** [comment]
Is this different from https://github.com/amacneil/dbmate/issues/34?

**Comment by MarkMurphy** [comment]
> Is this different from #34?

Yes, it would query the schema_mirgations table and then print the most recently installed version (if any).

ie. `20171127021917`

This is distinct from the `status` command which might show something like this:

![image](https://user-images.githubusercontent.com/873474/38180612-5a9437ce-3604-11e8-9bfa-7c3f6b174e94.png)

**Comment by amacneil** [comment]
Closing in favor of https://github.com/amacneil/dbmate/issues/28 (status command). I don't think it makes sense to show the most recent migration version in isolation, because dbmate cannot guarantee that migrations were applied in order and that there are no unapplied older migrations.
