### ISSUE TITLE
What do you recommend for doing data migrations (not regular schema migrations)?

### ISSUE THREAD

**Issue by himat** [amacneil/dbmate#345]
I've used python with the sqlalechemy ORM before, and a benefit of an ORM that does migrations is that you can not only do regular schema migrations (i.e. create a new table, modify a table, etc.), but also that you can do `data migrations` where you for example want to change data in the database as a migration.

An example in pseudocode where we take all the recent books created in this imaginary db, and write to a new column that we may have created in a previous schema migration:
```
up:
  books = conn.query("select * from books where created_at > current_date() - '3 weeks'")
  for b in books:
     if b.type == 'ebook':
       b.code = 4
     else:
       b.code = 2
```

This would then be run as a migration in the database locally and in prod. 

Obviously since dbmate is not an ORM and doesn't have a real programming language to execute around it, it doesn't seem like it would be able to do this.

So what do you generally recommend for people to do for cases like these?

**Comment by amacneil** [comment]
You can easily use dbmate for data migrations as well as schema migrations, as long as you can express them in sql.

So you could write something like `update books set code = 4 where type = 'ebook'`.

It obviously wouldn't work if you need to incorporate business logic from your orm layer, but you can express most stuff as sql easily.

**Comment by himat** [comment]
Ah right yeah I realize I can do sql data migrations
But sometimes, using a normal programming language makes the migration way easier, so was wondering if there was any option in those cases
