### ISSUE TITLE
Clickhouse migrations: Error: driver: bad connection

### ISSUE THREAD

**Issue by Hubbitus** [amacneil/dbmate#392]
**Description**
```shell
time podman run --rm -it --name dbmate -v .:/host:z --workdir /host --network=host ghcr.io/amacneil/dbmate:1.16.2 -u clickhouse://default@127.0.0.1:8123/datamart dump
Error: driver: bad connection

real    3m0.693s
```

- Version: 1.16.2 (official docker container)
- Database: Clickhouse
- Operating System: Fedora Linux

**Steps To Reproduce**
To run clickhouse:
```shell
podman run -d --name test-clickhouse \
        --ulimit nofile=262144:262144 \
        --network=host \
        -v ./_data/clickhouse/data:/var/lib/clickhouse:z -v ./_data/clickhouse/logs:/var/log/clickhouse-server:z \
        -e CLICKHOUSE_DB=datamart \
                docker.io/clickhouse/clickhouse-server
```
Command to run migrations (dump scheme really) provided initially

**Expected Behavior**
Schema dumped.

Or, as bare minimum - in case of error, some details provided what is wrong!

**Comment by amacneil** [comment]
This happens only for dump, or for all commands?

The tests are passing and I don't see anything immediately wrong/different about your setup.

**Comment by Hubbitus** [comment]
For all commands

**Comment by Hubbitus** [comment]
It looks like port was provided wrong, but error message definitely may be improved.

**Comment by amacneil** [comment]
Glad you figured it out. 

That error is coming from the [clickhouse go driver](https://github.com/ClickHouse/clickhouse-go). I agree it's not particularly descriptive, but it should be fixed upstream not here. I did notice that we are using v1 and there is now a v2 so I will upgrade in case that helps.
