### ISSUE TITLE
Incorrect dump file: missing space before database name

### ISSUE THREAD

**Issue by Hubbitus** [amacneil/dbmate#393]
**Description**

```shell
$ podman run --rm -it --name dbmate -v .:/host:z --workdir /host --network=host ghcr.io/amacneil/dbmate:1.16.2 -u clickhouse://default@127.0.0.1:8123/datamart dump
$ head -7 db/schema.sql 

--
-- Database schema
--

CREATE DATABASE IF NOT EXISTSdatamart;
```

So, `CREATE DATABASE IF NOT EXISTSdatamart;` should have space after `IF NOT EXISTS` clause.

- Version: 1.16.2
- Database: Clickhouse
- Operating System: Fedora Linus (run official docker container)

**Comment by Hubbitus** [comment]
Thank you very much.
When new tag and docker images will be available?

**Comment by amacneil** [comment]
Done! https://github.com/amacneil/dbmate/releases/tag/v2.0.0
