### ISSUE TITLE
Absolute path for migration directory is no longer working

### ISSUE THREAD

**Issue by blinktag** [amacneil/dbmate#403]
v2.0.0 broke the ability to specify an absolute path for the migrations directory.

The culprit is likely https://github.com/amacneil/dbmate/pull/388/files#diff-85e7f15f76b0a01f7ef13c1a5e83e93ba61401694dc5118dba4180cc8f4d0a59R73 which will cause any path to be prefixed with the argument passed to `DirFS()`

- Version: v2.0.0
- Database: postgres
- Operating System: alpine

**Steps To Reproduce**

The following command works correctly with v1.16.2:

```
$ dbmate -d /migrations migrate
```

Upgrading to v2.0.0 causes the following error:

```
Error: could not find migrations directory `/migrations`
```

**Expected Behavior**

Absolute paths should work as with previous versions

**Comment by amacneil** [comment]
Derp
