### ISSUE TITLE
How use in Windows?

### ISSUE THREAD

**Issue by Stunext** [amacneil/dbmate#41]
I have problems with "dbmate" in windows installed using "go get -u github.com/amacneil/dbmate". 
"dbmate command not found"

**Comment by emansom** [comment]
Make sure `GOPATH`\bin is in your `PATH` environment variable

**Comment by Samlof** [comment]
Is it possible to have a version without sqlite, or precompiled one? Getting gcc, cygwin and mingw working to compile it in windows sucks.

**Comment by emansom** [comment]
@Samlof If you are using Windows 10, consider using [WSL2](https://devblogs.microsoft.com/commandline/wsl-2-is-now-available-in-windows-insiders/) in combination with the [new terminal](https://devblogs.microsoft.com/commandline/introducing-windows-terminal/).

**Comment by amacneil** [comment]
It's very easy to build without sqlite (we already do this for the musl linux variant). I'll try to build a windows exe and see if I can publish this.

**Comment by faizalmansor** [comment]
How do you build without sqlite?

**Comment by amacneil** [comment]
Per https://github.com/amacneil/dbmate/pull/89, for now you can disable sqlite with the environment variable `CGO_ENABLED=0`:

```
GOARCH=amd64 GOOS=windows CGO_ENABLED=0 go build $(BUILD_FLAGS) -o dist/dbmate-windows-amd64.exe .
```

Let me see if I can get sqlite support working too.

**Comment by amacneil** [comment]
Windows binaries are now published! Please let me know if you encounter any issues with them.
