### ISSUE TITLE
Protection from accidental database dropping

### ISSUE THREAD

**Issue by Pashugan** [amacneil/dbmate#43]
I am a little bit worried that there is no confirmation before dropping a database. A single slip-up in typing can ruin all the data on a production server.

With all respect to the simplicity of the original design, I see the solution as an interactive confirmation with printing the host[:port], user and database name in the prompt to make sure the user understands what s/he is going to do, and the --force|-f option for use in scripts.

Are you interested in implementing this? Thanks.

**Comment by amacneil** [comment]
Following up here - I haven't been able to convince myself that this is a useful feature. It would still be just as easy to accidentally drop your production database using the `-f` flag (e.g. running your dev script against production).

I definitely have seen carnage before from running dev scripts against production, I just don't know that this will actually solve the problem (and meanwhile breaks backwards compatibility for existing users).

**Comment by amacneil** [comment]
Closing issue per comment above. Please feel free to chime in if there are use cases I have missed here.

**Comment by jgonera** [comment]
@amacneil alternative proposal: what if `dbmate drop` always required `database_name` as an argument? This way if I name my databases differently depending on the environment (`my_app_dev`, `my_app_prod`) running the command in the wrong environment would not cause any harm (e.g. running `dbmate drop my_app_dev` in production). Not sure how to solve this for SQLite (maybe file name instead?).

**Comment by amacneil** [comment]
I would suggest removing the drop database privilege from your production database user. That will prevent this issue.

**Comment by jgonera** [comment]
From what I gathered it's not that easy with MySQL. You can only remove the DROP privilege for everything (tables too), not just databases:

- https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html#priv_drop
- https://dba.stackexchange.com/a/27374/274480

(MySQL was not my choice, it's an inherited database)
