### ISSUE TITLE
The migration lock is not released after terminating the migration

### ISSUE THREAD

**Issue by yegor86** [amacneil/dbmate#460]
**Description**

- Version: 2.3.0
- Database: MySQL
- Operating System: MacOS

**Steps To Reproduce**
1. $DATABASE_URL points to a Mysql DB with noticeable work load 
2. Execute a migration file, which is supposed to change column type in an empty table
```shell
dbmate -e DATABASE_URL --migrations-dir . up
```
3. Experience Database and upstream service get out of service because dbmate applied READ LOCK to the entire schema
4. Cancel dbmate excution 
5. Contemplate that READ LOCK retains unless we kill the process that locks the schema. The process can be found in PROCESSLIST table.

**Expected Behavior**
* The READ LOCK gets release after aborting the dbmate execution
* dbmate locks table by table while applying the changes instead of locking all the schema at once and for all

**Comment by dossy** [comment]
Hi, @yegor86.  It's not clear to me how this is a dbmate bug?  dbmate itself does not acquire any metadata locks on its own when applying migrations on MySQL targets.

If you are using a new enough version of MySQL that [supports online DDL](https://dev.mysql.com/doc/refman/8.0/en/innodb-online-ddl.html), you could write your migration files to take advantage of it.

If you forcefully terminate dbmate's execution, then dbmate won't have an opportunity to gracefully clean up its connection to the server, and it is [a long-standing behavior of MySQL to not terminate client queries upon network connection disconnection](https://stackoverflow.com/questions/28625362/mysql-query-running-even-after-losing-connection), requiring a DBA to kill the process from the server side if the process requires terminating.

I don't think there's anything that can be done by way of change to dbmate to address either of these things.

**Comment by dossy** [comment]
As everything described in this issue is either expected behavior, or something we cannot do anything about by a change to dbmate, I'm going to close this issue.  If there's a proposal for a change to dbmate that could help here, please re-open this issue or open a new one outlining the change.  Thanks!
