### ISSUE TITLE
Wait for Postgres to be ready

### ISSUE THREAD

**Issue by frafra** [amacneil/dbmate#490]
**Description**

Hi!
I use dbmate as container. It works great, but the container sometimes fails to run, since it does not wait for Postgres to be ready. Other programs often use `pg_isready` or similar within the entrypoint, by trying to establish a connection before running the program, but dbmate Dockerfiles use the entrypoint to run the command itself, which is a pattern mostly used by CLI tools.

**Comment by dossy** [comment]
@frafra Does using `--wait` not solve the issue for you?

https://github.com/amacneil/dbmate#command-line-options

> `--wait` - wait for the db to become available before executing the subsequent command _(env: `DBMATE_WAIT`)_

**Comment by frafra** [comment]
It looks that `--wait` is not supported in 2.8.0. `dbmate wait` has to be used instead. It works :)
