### ISSUE TITLE
Dump the database schema to sql file

### ISSUE THREAD

**Issue by amacneil** [amacneil/dbmate#5]
Similar to Rails, we should dump the current database schema to a `db/schema.sql` file after running migrations.

This allows developers interacting with a git repo to better track the current state of a database (e.g. when reviewing pull requests, it's much easier to tell what has changed versus reviewing a single migration without context).

I don't believe this is possible to do with the mysql/postgres libraries, so we may need to shell out to mysqldump/pg_dump if they are available, and either error or fail silently if not available.

Suggested changes:

* `dbmate migrate` - should automatically dump the current schema after applying migrations
* `dbmate dump` - new command: should dump the current schema

**Comment by greglearns** [comment]
+1
