### ISSUE TITLE
no schema has been selected to create "schema_migrations" in

### ISSUE THREAD

**Issue by mgtest42** [amacneil/dbmate#50]
```
$ DATABASE_URL="postgres://root@localhost:5432/test12?sslmode=disable" dbmate up
Error: pq: no schema has been selected to create "schema_migrations" in
```
What does it mean?
I've created migration file with the creation of a couple of tables then I'm trying to migrate and getting this error. Maybe you have any ideas?

**Comment by amacneil** [comment]
Hi there - can you try again using v1.4.1 which I just released?
