### ISSUE TITLE
Embedded FS on Windows

### ISSUE THREAD

**Issue by Dissociable** [amacneil/dbmate#536]
**Description**
Basically, this is a bug only for Windows. `readMigrationsDir` sets the dir path via `filepath.Clean(dir)` which changes the `/` to `\` on Windows.
`fs.ReadDir` Is not able to handle that. changing `filepath.Clean(...)` to `path.Clean(...)` would simply fix it.

- Version: v2.14.0
- Database: Postgresql
- Operating System: Windows 10

**Steps To Reproduce**
```
//go:embed migrate/migrations/*
var EmbeddedMigrations embed.FS


	dbMate := dbmate.New(getAddr(dbName))
	dbMate.FS = ent.EmbeddedMigrations
	dbMate.MigrationsDir = []string{"migrate/migrations"}
	fmt.Println("Migrations:")
	migrations, err := dbMate.FindMigrations()
	if err != nil {
		panic(err)
	}
```

**Expected Behavior**
Find the embedded files at `migrate/migrations`

**Comment by dossy** [comment]
@Dissociable thanks for reporting this.

This makes me wonder: is it worth investing time in extending our CI test to add a Windows runner to test dbmate on, as well?  Similarly, should we add a macOS runner, too?

I know that GitHub hosted Windows and Mac action runners are [considerably more expensive](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#minute-multipliers), and I don't know if @amacneil wants to incur those costs for the project or not.

**Comment by boludoz** [comment]
@Dissociable contact with me in discord
