### ISSUE TITLE
Any reason to not store the list of applied migrations in the db

### ISSUE THREAD

**Issue by ysaakpr** [amacneil/dbmate#54]
Isnt it better to store the applied migrations in the database migrations table.

**Comment by mokxter** [comment]
Hi @ysaakpr 

From what I know, dbmate is already saving the list of applied migrations in the db. It saves it to the schema_migrations table.

![image](https://user-images.githubusercontent.com/3540938/45472299-642cb980-b766-11e8-877b-fd4a316d856a.png)

**Comment by ysaakpr** [comment]
Only the version details of last applied migrations are stored.

**Comment by amacneil** [comment]
dbmate stores every applied migration in the database table, this is explicitly designed to avoid race conditions between engineers working on separate PRs/commits. Let me know if I'm missing something here.
