### ISSUE TITLE
schema dump includes `AUTO INCREMENT`

### ISSUE THREAD

**Issue by david-a** [amacneil/dbmate#56]
Hi,

When I `dbmate migrate` the schema dump includes the current `AUTO INCREMENT` of each table, which is bad since if I want to import the schema as is (without going through all the migrations) to a server or another computer it will start the row count from where my local table ends.

Thanks

**Comment by david-a** [comment]
I do work with mysql currently, thanks.

**Comment by david-a** [comment]
It seems like a known issue, but it can be resolved with the `--skip-auto-increment` flag
source: https://stackoverflow.com/questions/15656463/mysqldump-export-structure-only-without-autoincrement

**Comment by paulovitorbal** [comment]
I will try to solve this in my fork. I will make a PR asap.

**Comment by iwata** [comment]
@paulovitorbal where is your PR?

**Comment by shames0** [comment]
It seems the mentioned `--skip-auto-increment` doesn't actually exist for `mysqldump` unless you have "GUI Tools". So, I took a stab at a PR for this. Interested in any feedback.
