### ISSUE TITLE
DB connection strings do not support exclamation points in password

### ISSUE THREAD

**Issue by iceflow19** [amacneil/dbmate#57]
I was getting an "Error 1045: Access denied for user...", given a valid connection string. Checked privileges and made sure everything was right on database side. It seems that mysql is fine with connection strings with exclamation points in them, while net/url mangles them and passes them to mysql as %21, which mysql interprets literally.

**Comment by fbiasion** [comment]
DB connection strings do not support also the character @ (at) in password.
