### ISSUE TITLE
Postgres can add values to enum inside transactions

### ISSUE THREAD

**Issue by jakajancar** [amacneil/dbmate#585]
The readme says:

> transaction
> 
> transaction is useful if you need to run some SQL which cannot be executed from within a transaction. For example, in Postgres, you would need to disable transactions for migrations that alter an enum type to add a value
> 

I was surprised to read this, as it hasn't been my experience. Turns out adding enum values [has worked within transactions](https://stackoverflow.com/a/53150621/70430) since v12 (released 2019).

Might want to add a note that this only applies to super old versions of PG or come up with an example where it's still relevant.

**Comment by amacneil** [comment]
Thanks for the info, that comment must have been written a long time ago. 

I removed the incorrect statement, but kept the example since I don't have a better one.
