### ISSUE TITLE
embed the migration time in the file

### ISSUE THREAD

**Issue by cpwais** [amacneil/dbmate#6]
It appears that the timestamp prefix of the schema migration files are used to indicate the ordering of migrations.  This feature prohibits using completely custom filenames (e.g. copying a file and changing the suffix and/or using more human-readable timestamps).  Moreover, if the filenames are incorrect (or there's a tie in the dates) then migrations could be applied in the wrong order.  To resolve this issue, the migration times could be embedded in the files; furthermore `dbmate new` could ensure a new migration occurs after all existing ones.  Additionally it could be helpful to have a tool that can verify the order in which migrations get applied.

**Comment by amacneil** [comment]
I don't quite follow what the issue is. If timestamps were embedded in the files instead of a filename prefix, there would still be potential for them to be incorrect (or duplicates) if you copy a file and don't change the timestamp. Having them in the filename is nice because it means that migration files are listed in the order that they should be applied.

**Comment by cpwais** [comment]
One of my use cases is being able to create a migration file w/out having dbmate installed.

**Comment by amacneil** [comment]
Sorry, I still don't follow. You can easily create a new migration file without having dbmate installed. As far as naming convention goes, it's just `version_description.sql`, where version is in `YYYYMMDDHHmmSS` format, so you can generate names following that convention from any script etc.

The version number technically doesn't even need to be a timestamp, so you could just as easily choose to name your migrations `1_foo.sql`, `2_bar.sql` etc (keep in mind they will always be applied in alphabetic order, so you probably don't want to mix integers and timestamps). The only reason we use a timestamp by default is that it avoids conflicting version numbers being generated by multiple developers working on different branches of the same project.
