### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by davbeck** [amacneil/dbmate#64]
I've been using dbmate with a node project. It works great but it would be nice if I could integrate it with the rest of my projects dependencies. While NPM is focused on Javascript, you can publish any binary to the repository (see https://github.com/sanathkr/go-npm for a go specific tool and instructions on doing this).

This would not only make it easier to use with node projects, but for some users would make it easier to install since NPM handles cross platform binaries automatically. You would even get support for `npx dbmate`, which lets you run a binary without explicitly installing it first. This would also simplify using it on Heroku.

**Comment by amacneil** [comment]
This is a great idea, thanks! I'll publish an npm package when I get a chance.

**Comment by water-a** [comment]
> This is a great idea, thanks! I'll publish an npm package when I get a chance.

@amacneil Will this ever be done? It'd be great to have so we don't have to place all the binaries in the repo to invoke it on all platforms.

**Comment by amacneil** [comment]
There is https://www.npmjs.com/package/dbmate. It is not fully integrated into our CI yet and I have not had time to do so. But it is in a working state.

**Comment by amacneil** [comment]
Added npm package in https://github.com/amacneil/dbmate/pull/400.
