### ISSUE TITLE
MySQL 8 Support?

### ISSUE THREAD

**Issue by NTanzeel** [amacneil/dbmate#67]
It seems like MySQL 8 databases aren't supported due to the new authentication method. I get the following error when running `dbmate up` using the brew OSX package:

```Error: this authentication plugin is not supported```

**Comment by amacneil** [comment]
I did some research, mysql 8 should be fixed in github.com/go-sql-driver/mysql v1.4.1 which I introduced in b417f82e644421530ce56ee178f4ed3627212810, but have not tagged a new release since then. Will release shortly.

**Comment by amacneil** [comment]
Fixed in v1.5.0
