### ISSUE TITLE
dbmate wait assumes "postgres" database exists

### ISSUE THREAD

**Issue by cnorthwood** [amacneil/dbmate#78]
This assumption doesn't hold true for DigitalOcean's managed databases, where the default postgres database does not get created. I think this is the appropriate bit of code in question: https://github.com/amacneil/dbmate/blob/master/pkg/dbmate/postgres.go#L30. I'm assuming this is so the wait doesn't fail if the database doesn't exist yet, but there's no guarantee postgres exists either, so I'm not sure what the suggest.

**Comment by amacneil** [comment]
This is interesting. The database named `postgres` is a system database and from what I can tell [should be created on every server by default](https://www.postgresql.org/docs/9.5/manage-ag-createdb.html). This internal database is also how the `createdb` cli command works. I wonder if it exists for DO but their default provisioned user doesn't have permission to access it.

Out of interest, do the `dbmate create` and `dbmate drop` commands also not work? These also currently rely on the postgres system database.

**Comment by cnorthwood** [comment]
For createdb to work on DO you have to specify the `--maintenance-db` command line option. It is slightly annoying how they've set it up. I've not tried using the create/drop commands in dbmate (the way I have it set up is for an external process to provision the database which logs in as a user which can create databases and creates the user, and then the application connects with a more limited set of permissions and uses dbmate to apply any pending migrations)
