### ISSUE TITLE
Skips some migrations 

### ISSUE THREAD

**Issue by TusharSheth** [amacneil/dbmate#82]
- I have more than 5 migrations files. There have been issues where dbmate doesn't apply schema change to databases though it prints that migration name in console.

**Comment by amacneil** [comment]
The code is pretty simple so I can't imagine why this might happen. Are you able to reproduce it?

**Comment by TusharSheth** [comment]
Yes. We are facing this issue more than often. How can I post the files? (Those are actually pretty big scripts)

**Comment by amacneil** [comment]
Yes, can you create a minimal reproduction? E.g. try to reproduce with simpler migrations. Once you do that you can post it on GitHub. 

Also, which version are you using?

**Comment by TusharSheth** [comment]
@amacneil 

I am using 
### dbmate version 1.4.1

you can try with below migrations 
1.  20181227123144_create_contributors.sql

> -- migrate:up
> CREATE TABLE IF NOT EXISTS contributors (
> 	id INT NOT NULL DEFAULT unique_rowid(),
> 	project_id INT NOT NULL,
> 	contributor_id INT NOT NULL,
> 	CONSTRAINT pk_contributors PRIMARY KEY (id ASC),
> 	FAMILY "primary" (id, project_id, contributor_id)
> );
> 
> -- migrate:down
> DROP TABLE IF EXISTS contributors;
> 

2. 20190311065206_contributors_sequence

> -- migrate:up
> -- Create contributor sequence
> ALTER TABLE contributors ADD COLUMN IF NOT EXISTS sequence INT NOT NULL DEFAULT 0;
> 
> -- migrate:down
> ALTER TABLE contributors DROP COLUMN IF EXISTS sequence;

### run 

> **dbmate migrate.** 

### error 
> Error: pq: relation "contributors" does not exist

**Comment by amacneil** [comment]
I assume based on the sql dialect above that you are using CockroachDB?

I created the migrations you specified, tried applying them against an empty database around 100 times, and was not able to reproduce this issue.

Please ensure you are using the latest version of dbmate (there was an issue with migrations being applied out of order prior to version 1.2.0).

If you are still able to reproduce this issue, please post a link to a minimal github repo containing a docker file, dbmate, and a script to reproduce it.
