### ISSUE TITLE
url.URL does not support DSN format anymore

### ISSUE THREAD

**Issue by mmailhos** [amacneil/dbmate#86]
Due to some recent changes in `net/url` package, a `github.com/go-sql-driver/mysql#Config.FormatDSN` resulting string can not be parsed by `net/url/#Parse`

The `net/url` package now parses an URL following more closely RFC 3986; therefore a MySQL DSN string such as the following one would not be parsed anymore:

```
_, err = url.Parse("mysql://boulder@tcp(localhost:3306)/boulder_test?parseTime=true")
if err != nil {
	fmt.Println(err)
}
// parse mysql://boulder@tcp(localhost:3306)/boulder_test?parseTime=true: invalid port ":3306)" after host
```

The `dbmate.New` constructor should be kept compatible with the standard MySQL DSN format and not (necessarily) rely on *url.URL.

A work-around is to manually build a string such as:
```
sqlURL := fmt.Sprintf("mysql://%s:%s@%s/%s", sqlConfig.User, sqlConfig.Passwd, sqlConfig.Addr, sqlConfig.DBName)
u, _ := url.Parse(sqlURL)
dbmate.New(u)
```

References
https://play.golang.org/p/jUs0pRjjn_Q
https://github.com/golang/go/commit/61bb56ad63992a3199acc55b2537c8355ef887b6
https://github.com/golang/go/issues/33646

**Comment by MathieuMailhos** [comment]
> I'm not sure I understand the problem. Regarding the constructor, are you using dbmate as a library or a CLI?

As a library.

> Is there a problem with using a URL such as `mysql://boulder@localhost/boulder_test?parseTime=true`?

No but there is a problem with this, for example:
```
sqlConfig := &mysql.Config{
	User:                 "root",
	Passwd:             "secret",
	Addr:                 "localhost:3306",
	Net:		          "tcp",
	DBName:           "mysql",
	AllowNativePasswords: true,
}
_, err := url.Parse("mysql://" + sqlConfig.FormatDSN())
// DNS:  root:secret@tcp(localhost:3306)/mysql?maxAllowedPacket=0
// parse mysql://root:secret@tcp(localhost:3306)/mysql?maxAllowedPacket=0: invalid port ":3306)" after host
```

https://play.golang.org/p/E12R0IG4X_7

> Dbmate is intended to take a URL connection string, not a MySQL DSN. 

Ok, that's not an issue if this is by design then. I just think it would be good to follow MySQL DSN format.

**Comment by amacneil** [comment]
I see. As you noticed, when using dbmate as an API the libraries assume that your connection string is a valid URL. We assume that any database connection string can be formatted as a url (and in fact many/most languages can support a url connection string).

The DSN format you're using above seems to be specific to the Go MySQL driver, correct? I can't find any references to it in the MySQL documentation. The reason I ask is that if it were a standard cross-language MySQL connection string format then it might make sense for us to support it (even though this would require some significant refactoring), but if it's unique to the Go MySQL driver then I think it makes more sense to leave this out.

In the meantime, you can generate a valid connection URL from your `mysql.Config` very easily using `fmt.Sprintf`.

**Comment by amacneil** [comment]
I looked further into this. Supporting arbitrary strings instead of a `url.URL` requires pretty significant refactoring since we need to be able to parse the connection string before providing it to the driver (e.g. for connecting to the root database), and each go database driver expects different things.

I'm not convinced this is worth adding support for considering the workaround you suggested is pretty simple. Dbmate is designed to support multiple databases with a standardized interface, and for now it's simpler if we keep the interface requiring a URL.
