### ISSUE TITLE
Running dbmate with docker or docker-compose run

### ISSUE THREAD

**Issue by mattking17** [amacneil/dbmate#87]
Hello,

I want to run dbmate inside the provided docker container, but it's not clear to me how this works in practice. I'm learning docker at the same time here so this may be part of my ignorance.

If I run the `dbmate` using `docker run`, then it writes the migration file inside the docker container that was created. But how would I go about accessing that file again? I tried specifying the migrations directory using the `--migrations-dir` command, but still can't find a way to edit the migration file that was created.

**Comment by amacneil** [comment]
Sorry for the confusion! I've updated the readme with better instructions.

In short, you need to bind mount your local working directory into the dbmate docker container. So your command should look like this:

```sh
docker run --rm -it -v "$(pwd)"/db:/db amacneil/dbmate new create_users_table
```
