### ISSUE TITLE
dbmate with postgres - Error: pq: must be owner of extension uuid-ossp

### ISSUE THREAD

**Issue by TalyGin** [amacneil/dbmate#97]
I'm trying to use dbmate to bring up database on newly provisioned postgres instance.
It does not matter if database exists or not, as well as extension uuid-ossp created with schema public or not. The db instance is AWS RDS PostgreSQL 9.5.
dbmate fails to execute <datetime>_init.sql script from misgrations folder.
As the result, database created, but initial script is not executed.
The error is:
`Error: pq: must be owner of extension uuid-ossp`
I'm not sure what is pq in this context, and how to fix it.
Any ideas?

**Comment by wkalt** [comment]
You might want to put

```
create extension "uuid-ossp";
```
at the top of _init.sql. It's not a dbmate issue - you're likely trying to create uuids without installing the necessary postgres extension.

**Comment by TalyGin** [comment]
@wkalt Yes, I tried it already, added to template1 before I'm creating the new db.
`create extension if not exists uuid-ossp with schema public;`
It does not work. Getting the same error.

**Comment by amacneil** [comment]
It sounds like for whatever reason the user you're using to postgres doesn't have permission to use that extension. This isn't a dbmate issue, I expect you will see the same error if you try running that same command using `psql`.

I recommend trying it with the default/root user created by RDS when you set up the database. If that doesn't work, try creating a completely new RDS instance as a troubleshooting step.

**Comment by daprieto1** [comment]
ALTER EXTENSION postgis UPDATE;
ALTER EXTENSION postgis_topology UPDATE;

-- yes run it twice
SELECT postgis_extensions_upgrade();
SELECT postgis_extensions_upgrade();
